main_window:
  compose: viewport

viewport:

media_loader:
  compose: main_window


screen_info:
  compose: main_window

app_starter:
  compose: 
    - main_window
    - mode_wrangler
    - main_menu_mode
    - debug_server
    - game_master

debug_server:

mode_wrangler:
  compose: main_window

level_factory:
  system_context: this_context
  compose: debug_server, media_loader

main_menu_mode:
  compose: media_loader, main_window, game_master

game_master:
  compose: mode_wrangler, level_factory, game_config

game_config:

svg_shape_parser:

svg_loader:
  compose: media_loader

picture_factory:
  compose:
    - media_loader

space_holder:

physical_factory:
  compose:
    - space_holder

joint_factory:
  compose:
    - space_holder

dump_truck_factory:
  object_context: this_context

terrain_factory:
  compose:
    - svg_loader
    - space_holder

background_factory:
  compose:
    - media_loader


slider_factory:
  compose:
    - joint_factory
    - physical_factory
    - media_loader

fruit_factory:
  compose:
    - space_holder
    - media_loader
    - svg_loader
    - physical_factory
    - svg_shape_parser

crate_factory:
  compose:
    - picture_factory
    - fruit_factory

scenery_factory:
  compose:
    - picture_factory

shape_drawing:

+dump_truck:
  dump_truck_controls:

  dump_truck:
    compose:
      - space_holder
      - media_loader
      - physical_factory
      - dump_truck_controls

+truck_level_1:
  mode:
    class: PhysicsLevelMode
    compose: space_holder

  simulation:
    compose:
      - mode
      - space_holder

  truck_level_1_setup:
    compose:
      - mode
      - simulation
      - terrain_factory
      - background_factory
      - dump_truck_factory
      - crate_factory
      - viewport_controller
      - svg_loader
      - media_loader
      - physical_factory
      - scenery_factory
      - joint_factory
      - shape_drawing

  viewport_controller:
    compose:
      - simulation
      - viewport

+workshop:
  mode:
    class: PhysicsLevelMode
    compose: space_holder

  viewport_controller:
    compose:
      - simulation
      - viewport

  simulation:
    compose:
      - mode
      - space_holder

  workshop_room:
    compose:
      - mode
      - simulation
      - terrain_factory
      - background_factory
      - dump_truck_factory
      - crate_factory
      - viewport_controller
      - workshop_zones_controller
      - svg_loader

  workshop_zones_controller:
    compose:
      - simulation
      - media_loader
      - svg_loader

  sliders_controller:
    compose:
      - simulation
      - slider_source

  slider_source:
    compose: 
      - slider_factory
      - svg_loader

