main_window:
  compose: viewport

viewport:

media_loader:
  compose: main_window

screen_info:
  compose: main_window

app_starter:
  compose: 
    - main_window
    - mode_wrangler
    - main_menu_mode
    - debug_server
    - game_master

debug_server:

mode_wrangler:
  compose: main_window

level_factory:
  system_context: this_context
  compose: debug_server, media_loader

main_menu_mode:
  compose: media_loader, main_window, game_master

game_master:
  compose: mode_wrangler, level_factory, game_config

game_config:

+workshop:
  mode:
    class: LevelMode

  space_holder:

  viewport_controller:
    compose:
      - simulation
      - viewport

  simulation:
    compose:
      - mode
      - space_holder

  workshop_room:
    compose:
      - mode
      - screen_info
      - main_window
      - space_holder
      - media_loader
      - workshop_svg_holder

  workshop_zones_controller:
    compose:
      - simulation
      - media_loader
      - workshop_svg_holder

  svg_shape_parser:

  workshop_svg_holder:
    compose:
      - media_loader

  physical_factory:
    compose:
      - space_holder

  truck_controller:
    compose:
      - simulation
      - truck_factory
      - viewport_controller
      - workshop_zones_controller
      - workshop_svg_holder

  truck_factory:
    object_context: this_context
  
  rain_controller:
    compose:
      - simulation
      - space_holder
      - media_loader

  crates_controller:
    compose:
      - simulation
      - workshop_svg_holder
      - crate_factory
      - fruit_factory


  crate_factory:
    compose:
      - picture_factory

  picture_factory:
    compose:
      - media_loader

  fruit_factory:
    compose:
      - space_holder
      - media_loader
      - workshop_svg_holder
      - physical_factory
      - svg_shape_parser

#  attachment_experiment:
#    compose:
#      - space_holder
#      - simulation
#      - workshop_svg_holder

  sliders_controller:
    compose:
      - simulation
      - slider_source

  slider_source:
    compose: 
      - slider_factory
      - workshop_svg_holder

  slider_factory:
    compose:
      - joint_factory
      - physical_factory
      - media_loader
  
  joint_factory:
    compose:
      - space_holder

  +dump_truck:
    truck_controls:

    truck:
      compose:
        - simulation
        - main_window
        - space_holder
        - media_loader
        - physical_factory
        - truck_controls
