main_window:

media_loader:
  compose: main_window

screen_info:
  compose: main_window

app_starter:
  compose: 
    - main_window
    - mode_wrangler
    - main_menu_mode
    - debug_server
    - game_master

debug_server:

mode_wrangler:
  compose: main_window

level_factory:
  system_context: this_context
  compose: debug_server, media_loader

main_menu_mode:
  compose: media_loader, main_window, game_master

game_master:
  compose: mode_wrangler, level_factory, game_config

game_config:

+workshop:
  mode:
    class: LevelMode

  space_holder:

  workshop_room:
    compose:
      - mode
      - screen_info
      - main_window
      - space_holder

  physical_factory:
    compose:
      - space_holder

  truck_controller:
    compose:
      - mode
      - truck_factory

  truck_factory:
    object_context: this_context
  
  rain_controller:
    compose:
      - mode
      - space_holder
      - media_loader

  +dump_truck:
    truck:
      compose:
        - main_window
        - space_holder
        - media_loader
        - physical_factory
