#!/usr/bin/ruby
require File.expand_path(File.dirname(__FILE__) + "/../config/environment")


class MW < Window
  def initialize(file)
    super(100,100,false)
    s = Gosu::Song.new(self,file)
    s.play
  end
  def button_down(id)
    if id == Gosu::Button::KbEscape then
      close
    end
  end
end

file = ARGV.shift
raise "Need a filename" unless file
MW.new(file).show
